[random]
quotes = [
	"",
	"",
	"",
	"",
	"",
]

[capture] # when opponent captures
pawn = [
	"",
	"",
	"",
	"",
	"",
]

knight = [
	"",
	"",
	"",
	"",
	"",
]

bishop = [
	"",
	"",
	"",
	"",
	"",
]

rook = [
	"",
	"",
	"",
	"",
	"",
]

queen = [
	"",
	"",
	"",
	"",
	"",
]

[take]
pawn = [
	"",
	"",
	"",
	"",
	"",
]

knight = [
	"",
	"",
	"",
	"",
	"",
]

bishop = [
	"",
	"",
	"",
	"",
	"",
]

rook = [
	"",
	"",
	"",
	"",
	"",
]

queen = [
	"",
	"",
	"",
	"",
	"",
]

rare = [
	"",
	"",
	""
]



[check] # opponent

quotes = [
	"",
	"",
	"",
	"",
	"",
]

[checked] # Ferris
quotes = [
	"",
	"",
	"",
]

[checkmate]

quotes = [
	"",
	"",
	"",
	"",
	"",
]
